# Sudoku

In [1]:
import numpy as np
import csv

In [2]:
sudoku = np.genfromtxt('../Data/sudoku/sudoku.csv',dtype='int', delimiter=',')
sefer = 0


In [3]:
#su = pd.DataFrame(sudoku)
su = np.array(sudoku)
su

array([[2, 0, 8, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 3, 0, 0, 2, 0],
       [0, 5, 0, 6, 0, 0, 4, 0, 7],
       [6, 1, 9, 0, 0, 0, 8, 3, 0],
       [0, 0, 0, 8, 9, 2, 0, 0, 0],
       [0, 2, 4, 0, 0, 0, 7, 5, 9],
       [7, 0, 5, 0, 0, 9, 0, 1, 0],
       [0, 4, 0, 0, 7, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 2, 0, 3]])

In [4]:
kalabalık_hücre = [[0,0,0],
                   [0,0,0],
                   [0,0,0]]
k_hücre  = np.array(kalabalık_hücre)

In [5]:
#s sayılar
s=[1,2,3,4,5,6,7,8,9]


In [6]:
ola_ki = [[0,0,0,0,0,0,0,0,0],
          [0,0,0,0,0,0,0,0,0],
          [0,0,0,0,0,0,0,0,0],
          [0,0,0,0,0,0,0,0,0],
          [0,0,0,0,0,0,0,0,0],
          [0,0,0,0,0,0,0,0,0],
          [0,0,0,0,0,0,0,0,0],
          [0,0,0,0,0,0,0,0,0],
          [0,0,0,0,0,0,0,0,0]]

ola = np.array((ola_ki),dtype =set) 

In [7]:
ola

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=object)

In [8]:
su

array([[2, 0, 8, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 3, 0, 0, 2, 0],
       [0, 5, 0, 6, 0, 0, 4, 0, 7],
       [6, 1, 9, 0, 0, 0, 8, 3, 0],
       [0, 0, 0, 8, 9, 2, 0, 0, 0],
       [0, 2, 4, 0, 0, 0, 7, 5, 9],
       [7, 0, 5, 0, 0, 9, 0, 1, 0],
       [0, 4, 0, 0, 7, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 2, 0, 3]])

In [9]:
#satırda kaç sıfır olduğu ve eksik sayılar
def satırdaki_eksik_sayı(satır):
    su_satırı_list = su[satır,:]
    c_yeri=[]
    c_eksik=[]
    sıfır = 0
    for k in s:
        if k in su_satırı_list:
            sıfır=sıfır #boşlaf
        else:
            for sat in range(9):
                if su_satırı_list[sat]==0:
                    c_yeri.append(sat)
            c_eksik.append(k)
            sıfır+=1
    return sıfır , c_eksik ,c_yeri

In [10]:
#kolonda kaç sıfır olduğu ve eksik sayılar
def kolondaki_eksik_sayı(kolon):
    su_kolonu_list = su[:,kolon]
    c_yeri=[]
    c_eksik=[]
    sıfır = 0
    for k in s:
        if k in su_kolonu_list:
            sıfır=sıfır #boşlaf
        else:
            for kol in range(9):
                if su_kolonu_list[kol]==0:
                    c_yeri.append(kol)
            c_eksik.append(k)
            sıfır+=1
    return sıfır , c_eksik , c_yeri

# Durum

In [11]:
durum = np.zeros((9,9,9))#durum[sayı,x,y]


In [12]:
# durum init hepsi 2
#durum[sayı,x,y]
durum[:,:,:]=2


In [13]:
def satır_kolon_tazele(sayı,x,y):
    for say in s:
        if say==sayı:
            durum[sayı-1,:,y]=0
            durum[sayı-1,x,:]=0
            durum[sayı-1,x,y]=1
        else:
            durum[say-1,x,y]=0
    return 

In [14]:
#ilk girilen sudokunun durum tazelemesi
#(hangi sayı varsa onun olduğu yer 1, olamayacağı yerler 0)
def durum_tazele():    
    for satır in range(9):
        for kolon in range(9):
            if su[satır,kolon]>0:
                dummy_sayı = su[satır,kolon]
                satır_kolon_tazele(dummy_sayı,satır,kolon)
    return        

In [15]:
durum_tazele()

In [16]:
def d(sayı): 
    return (durum[sayı-1,:,:])
    

# Hücre

In [17]:
def hücreyi_bil(x,y):
    if x in range(0,3):x1=0    
    if x in range(3,6):x1=3
    if x in range(6,9):x1=6  
    if y in range(0,3):y1=0
    if y in range(3,6):y1=3
    if y in range(6,9):y1=6  
    
    #hücre = durum[sayı-1:sayı,x1:x1+3,y1:y1+3]
    
    return x1,y1

In [18]:
def yer_uygunsa_suya_ekle(sayı,x,y):
    x1,y1 = hücreyi_bil(x,y)
    if  (su[x,y]==0)and (sayı not in su[:,y]) and (sayı not in su[x,:]) and  (sayı not in su[x1:x1+3,y1:y1+3]):
            su[x,y]=sayı  #eklendi
            durum_tazele()
        #else:
        #print(str(sayı)+" satır "+str(x)+" , kolon "+str(y)+" "+"için uygun değil")
    return
    

In [19]:
#durumdan bir sayı bulup suya eklemenin parçası
def  durumu_4_olanı_suya_ekle(): 
    for sayı in s:
        for xx in range(9):
             for yy in range(9):
                if  durum[sayı-1,xx,yy]==4:
                        
                        su[xx,yy]=sayı 
                        durum[sayı-1,xx,yy]=1
    durum_tazele()             
  

In [20]:
#bir hücrede "sayı" varsa o sayının hücresel durumunda 2 olan nokta olamaz 
def hücre_durum_tazele(sayı):
    for x1 in [0,3,6]:
        for y1 in [0,3,6]:
            #x1,y1=hücreyi_bil(x2,y2)
            a=durum[sayı-1:sayı,x1:x1+3,y1:y1+3].sum()
            hücre = durum[sayı-1:sayı,x1:x1+3,y1:y1+3]
            
            if a>1 and a%2!=0:
                hücre[hücre==2]=0
            if a==2 :
                hücre[hücre==2]=4
    durumu_4_olanı_suya_ekle()
    return

In [21]:
def en_kalabalık_hücreyi_bul():
    a = []
    xy = []
    for x1 in [0,3,6]:
        for y1 in [0,3,6]:
            yer=[x1,y1]
            xy.append(yer) 
            #if cell is full to ignore it: we append 0
            if su[x1:x1+3,y1:y1+3].sum()==45:
                a.append(0)
            else:    
                a.append(su[x1:x1+3,y1:y1+3].sum()    )
    maxy=np.argmax(a) 
    return xy[maxy]

In [22]:
hücre_durum_tazele(1)

In [23]:
def kaç_tane_çıktı(sayı):
    c=durum[sayı-1,:,:]
    kaç = c[c==1].sum()
    #print(sayı,kaç )
    return kaç
    

In [24]:
def sudaki_boşu_olan_satırlara_sayı_bul():
    #satırlarda boşluk buluyor
    
    for rr in range(9):
        sıfı=0
        eksik=[]
        yer=[]
        sıfı,eksik,yer=satırdaki_eksik_sayı(rr)
        if sıfı==0:
            return
        for t in range(sıfı):
            if sıfı==1:            
                #su[rr,yer[0]]=eksik[0]
                yer_uygunsa_suya_ekle(eksik[0],rr,yer[0])
            if sıfı==2:
                if eksik[0]in su[:,yer[0]]:
                    #diğeri konuyor                
                    #su[rr,yer[0]]=eksik[1] 
                    yer_uygunsa_suya_ekle(eksik[1],rr,yer[0])
                    #su[rr,yer[1]]=eksik[0]
                    yer_uygunsa_suya_ekle(eksik[0],rr,yer[1])
                    
                elif eksik[0]in su[:,yer[1]]:
                    #diğeri konuyor                
                    #su[rr,yer[0]]=eksik[0] 
                    yer_uygunsa_suya_ekle(eksik[0],rr,yer[0])
                    #su[rr,yer[1]]=eksik[1]
                    yer_uygunsa_suya_ekle(eksik[1] ,rr,yer[1])
            if sıfı==3:
                #print(sıfı,eksik,yer,eksik[0],yer[2],rr,su[:,yer[0]],su[:,yer[1]],su[:yer[2]])
                if (eksik[0] in su[:,yer[0]])and (eksik[0] in su[:,yer[1]])and (eksik[0]not in su[:,yer[2]]):
                    yer_uygunsa_suya_ekle(eksik[0],rr,yer[2])   
                if (eksik[0] in su[:,yer[0]])and (eksik[0]not in su[:,yer[1]])and (eksik[0] in su[:,yer[2]]):
                    yer_uygunsa_suya_ekle(eksik[0],rr,yer[1])   
                if (eksik[0]not in su[:,yer[0]])and (eksik[0] in su[:,yer[1]])and (eksik[0] in su[:,yer[2]]):
                    yer_uygunsa_suya_ekle(eksik[0],rr,yer[0]) 
                    
                if (eksik[1] in su[:,yer[0]])and (eksik[1] in su[:,yer[1]])and (eksik[1]not in su[:,yer[2]]):
                    yer_uygunsa_suya_ekle(eksik[1],rr,yer[2])   
                if (eksik[1] in su[:,yer[0]])and (eksik[1]not in su[:,yer[1]])and (eksik[1] in su[:,yer[2]]):
                    yer_uygunsa_suya_ekle(eksik[1],rr,yer[1])   
                if (eksik[1]not in su[:,yer[0]])and (eksik[1] in su[:,yer[1]])and (eksik[1] in su[:,yer[2]]):
                    yer_uygunsa_suya_ekle(eksik[1],rr,yer[0])   

                if (eksik[2] in su[:,yer[0]])and (eksik[2] in su[:,yer[1]])and (eksik[2]not in su[:,yer[2]]):
                    yer_uygunsa_suya_ekle(eksik[2],rr,yer[2])   
                if (eksik[2] in su[:,yer[0]])and (eksik[2]not in su[:,yer[1]])and (eksik[2] in su[:,yer[2]]):
                    yer_uygunsa_suya_ekle(eksik[2],rr,yer[1])   
                if (eksik[2]not in su[:,yer[0]])and (eksik[2] in su[:,yer[1]])and (eksik[2] in su[:,yer[2]]):
                    yer_uygunsa_suya_ekle(eksik[2],rr,yer[0])   

            if sıfı>3:
                olabileceği_yerler=np.zeros((sıfı))
                for eks1 in range(sıfı):
                    olabileceği_yerler_toplamı=0      #olabileceği yerlerin sayısı
                    for eks2 in range(sıfı):
                        if eksik[eks1] in su[:,yer[eks2]]:
                            olabileceği_yerler[eks2]=0   
                        else:    
                            olabileceği_yerler[eks2]=1    
                            olabileceği_yerler_toplamı+=1
                            tek_yer=yer[eks2]
                    if olabileceği_yerler_toplamı==1 : 
                        
                        yer_uygunsa_suya_ekle(eksik[eks1],rr,tek_yer)
                        #print(eksik[eks1],tek_yer,yer[tek_yer],rr)
            
              
    durum_tazele()

In [25]:
def sudaki_boşu_olan_kolonlara_sayı_bul():
    #kolonlardaki boşluklara sayı buluyor

    for rr in range(9):
        sıfı=0
        eksik=[]
        yer=[]
        sıfı,eksik,yer=kolondaki_eksik_sayı(rr)
        if sıfı==0:
            return
        
        for t in range(sıfı):
            if sıfı==1:            
                #su[yer[0],rr]=eksik[0]
                yer_uygunsa_suya_ekle(eksik[0],yer[0],rr)
            if sıfı==2:
                if eksik[0]in su[yer[0],:]:
                    #diğeri konuyor                
                    #su[yer[0],rr]=eksik[1] 
                    yer_uygunsa_suya_ekle(eksik[1],yer[0],rr)
                    #su[yer[1],rr]=eksik[0]
                    yer_uygunsa_suya_ekle(eksik[0],yer[1],rr)
                    
                elif eksik[0]in su[yer[1],:]:
                    #diğeri konuyor                
                    #su[yer[0],rr]=eksik[0]
                    yer_uygunsa_suya_ekle(eksik[0],yer[0],rr)
                    #su[yer[1],rr]=eksik[1]
                    yer_uygunsa_suya_ekle(eksik[1],yer[1],rr)
            if sıfı==3:
                if (eksik[0] in su[yer[0],:])and (eksik[0] in su[yer[1],:])and (eksik[0]not in su[yer[2],:]):
                    yer_uygunsa_suya_ekle(eksik[0],yer[2],rr)   
                if (eksik[0] in su[yer[0],:])and (eksik[0]not in su[yer[1],:])and (eksik[0] in su[yer[2],:]):
                    yer_uygunsa_suya_ekle(eksik[0],yer[1],rr)   
                if (eksik[0]not in su[yer[0],:])and (eksik[0] in su[yer[1],:])and (eksik[0] in su[yer[2],:]):
                    yer_uygunsa_suya_ekle(eksik[0],yer[0],rr) 
                    
                if (eksik[1] in su[yer[0],:])and (eksik[1] in su[yer[1],:])and (eksik[1]not in su[yer[2],:]):
                    yer_uygunsa_suya_ekle(eksik[1],yer[2],rr)   
                if (eksik[1] in su[yer[0],:])and (eksik[1]not in su[yer[1],:])and (eksik[1] in su[yer[2],:]):
                    yer_uygunsa_suya_ekle(eksik[1],yer[1],rr)   
                if (eksik[1]not in su[yer[0],:])and (eksik[1] in su[yer[1],:])and (eksik[1] in su[yer[2],:]):
                    yer_uygunsa_suya_ekle(eksik[1],yer[0],rr)   

                if (eksik[2] in su[yer[0],:])and (eksik[2] in su[yer[1],:])and (eksik[2]not in su[yer[2],:]):
                    yer_uygunsa_suya_ekle(eksik[2],yer[2],rr)   
                if (eksik[2] in su[yer[0],:])and (eksik[2]not in su[yer[1],:])and (eksik[2] in su[yer[2],:]):
                    yer_uygunsa_suya_ekle(eksik[2],yer[1],rr)   
                if (eksik[2]not in su[yer[0],:])and (eksik[2] in su[yer[1],:])and (eksik[2] in su[yer[2],:]):
                    yer_uygunsa_suya_ekle(eksik[2],yer[0],rr)   

            if sıfı>3:
                olabileceği_yerler=np.zeros((sıfı))
                for eks1 in range(sıfı):
                    olabileceği_yerler_toplamı=0      #olabileceği yerlerin sayısı
                    for eks2 in range(sıfı):
                        if eksik[eks1] in su[yer[eks2],:]:
                            olabileceği_yerler[eks2]=0   
                        else:    
                            olabileceği_yerler[eks2]=1   
                            olabileceği_yerler_toplamı+=1
                            tek_yer=yer[eks2]
                    if olabileceği_yerler_toplamı==1 : 
                        
                        yer_uygunsa_suya_ekle(eksik[eks1],tek_yer,rr)
                        

    durum_tazele()

# Ola

In [26]:
log_text=[[],[],[],[]]#xy,ola[xy],seçilen sayı,yer
log=[log_text]

In [27]:
def oladan_seç_suya_ekle():
    global sefer
    global en_küçük_ola_set_item
    global log_text, log
    
    found =0
    en_küçük_ola_set_item = 1
        
    xy=en_kalabalık_hücreyi_bul()  
    log_text[0]=xy
    

    while  found==0 or en_küçük_ola_set_item>9:        
        #hücreyle sınırlı for loop
        for xx in (0,1,2):
            x=xy[0]
            x+=xx
            for yy in (0,1,2):
                y=xy[1]
                y+=yy
                #sıfır olmamalı yoksa len olay çıkarıyor
                if ola[x,y]!=0 and su[x,y]==0:
                    if len(ola[x,y]) == en_küçük_ola_set_item:
                        sayı=ola[x,y][0]   
                        yer_uygunsa_suya_ekle(sayı,x,y)
                        found+=1
                        sefer+=1
                        log=[]
                        log_text[1]=ola[x,y]
                        log_text[2]=ola[x,y][0]
                        log_text[3]=[x,y]
                        log.append(log_text)
                        ola[x,y]=ola[x,y][1::] #kullandığımız sayıyı kaldırıyoruz
                        
                        return 
        if found==0: 
            log.append(log_text)
            en_küçük_ola_set_item+=1
            sefer=0
        #while buluncaya kadar    
    return           

In [28]:
def ola_lar():
    for x in range(9):
        for y in range(9):
            ola_set=[]
            ola_set_boyu=0
            #print(x,y,su[x,y],ola[x,y])
            
            if su[x,y]==0:
                for say in s:
                    tek_sayı=0
                    x1,y1=hücreyi_bil(x,y)
                    hücre = su[x1:x1+3,y1:y1+3]
                    if (say not in su[x,:])and(say not in su[:,y])and(say not in hücre):
                        ola_set.append(say)
                        ola[x,y]=ola_set
                        ola_set_boyu+=1
                                               
                if ola_set_boyu==1 :
                    #print(tek_sayı,ola_set,ola[x,y],x,y)
                    ola[x,y]=0
                    tek_sayı=ola_set.pop()
                    yer_uygunsa_suya_ekle(tek_sayı,x,y)                    
    return  

# Çalış

In [29]:
def çalış(kez):
       
    for do in range (kez):
        durum_tazele()
        sudaki_boşu_olan_kolonlara_sayı_bul()          
        sudaki_boşu_olan_satırlara_sayı_bul()
        ola = np.array((ola_ki),dtype =set)
        ola_lar()
        for say in s:
            hücre_durum_tazele(say)
         
    return
    

In [30]:
#ikili ola şıklarından birini kendi seçip ilerleyecek
def atarak_ilerle():
    global su
    global durum
    global ola
    global saklısu
    global saklıdurum
    global saklıola
    
    if sefer ==0:
        saklısu= np.copy(su)#su'yu sakladık artık suyu değiştirsek de saklısu değişmez
        saklıdurum = np.copy(durum)#durum'u sakladık
        saklıola = np.copy(ola)#ola'yı sakladık
    if sefer==1:
        su=np.copy(saklısu)
        durum=np.copy(saklıdurum)
        ola=np.copy(saklıola)
        
    oladan_seç_suya_ekle()
    
    

In [31]:
# -- main  --
def çöz():
    
    kaj=0
    kaj_tut=0
    bu_kaçıncı_aynı=0
    for deneme in range (30):
        çalış(30)
        kaj=0  
        
        for say in s:        
            kaj+=kaç_tane_çıktı(say)
        if kaj==81 :
            print(kaj)
            return
        if kaj_tut!=kaj:
            kaj_tut=kaj
        else:
            bu_kaçıncı_aynı+=1
        if bu_kaçıncı_aynı>2:
            bu_kaçıncı_aynı=0
            #print(kaj)
            oladan_seç_suya_ekle()
            #print(log)

In [32]:
çöz()

81.0


In [33]:
su

array([[2, 9, 8, 5, 4, 7, 3, 6, 1],
       [4, 6, 7, 9, 3, 1, 5, 2, 8],
       [3, 5, 1, 6, 2, 8, 4, 9, 7],
       [6, 1, 9, 7, 5, 4, 8, 3, 2],
       [5, 7, 3, 8, 9, 2, 1, 4, 6],
       [8, 2, 4, 1, 6, 3, 7, 5, 9],
       [7, 3, 5, 2, 8, 9, 6, 1, 4],
       [1, 4, 2, 3, 7, 6, 9, 8, 5],
       [9, 8, 6, 4, 1, 5, 2, 7, 3]])

In [34]:
t=0
for say in s:        
    kaj=kaç_tane_çıktı(say)
    t+=kaj
    print(kaj)
print(t)

9.0
9.0
9.0
9.0
9.0
9.0
9.0
9.0
9.0
81.0


In [35]:
ola

array([[0, [6, 7, 9], 0, 0, [1, 4], [1, 7], [1, 3, 6, 9], 0, 0],
       [[1, 4, 9], [6, 7], [1, 6, 7], [1, 4, 7, 9], 0, [1, 7, 8], [1, 5],
        0, [1, 6, 8]],
       [[1, 3, 9], 0, [1, 3], 0, [1, 2, 8], [1, 8], 0, [8, 9], 0],
       [0, 0, 0, [4, 7], 0, [4, 7], 0, 0, [2, 4]],
       [[3, 5], 0, 0, 0, 0, 0, 0, 0, 0],
       [[3, 8], 0, 0, 0, [1, 6], [1, 3, 6], 0, 0, 0],
       [0, [3, 6, 8], 0, [2, 3, 4], 0, 0, 0, 0, [4, 8]],
       [0, 0, [1, 2, 3, 6], 0, 0, [6, 8], [5, 9], 0, [5, 8]],
       [0, [6, 8], 0, 0, 0, 0, 0, [4, 7, 8, 9], 0]], dtype=object)

In [36]:
su

array([[2, 9, 8, 5, 4, 7, 3, 6, 1],
       [4, 6, 7, 9, 3, 1, 5, 2, 8],
       [3, 5, 1, 6, 2, 8, 4, 9, 7],
       [6, 1, 9, 7, 5, 4, 8, 3, 2],
       [5, 7, 3, 8, 9, 2, 1, 4, 6],
       [8, 2, 4, 1, 6, 3, 7, 5, 9],
       [7, 3, 5, 2, 8, 9, 6, 1, 4],
       [1, 4, 2, 3, 7, 6, 9, 8, 5],
       [9, 8, 6, 4, 1, 5, 2, 7, 3]])

In [37]:
sefer

0

In [38]:
durum

array([[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
        [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
        [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.]],

       [[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
        [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.]],

      